/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.gov.minambiente.vista.formulario;

import co.gov.minambiente.controlador.ControlStatistics;
import co.gov.minambiente.controlador.RequestFrequency;
import co.gov.minambiente.controlador.database.RequestsDatabase;
import co.gov.minambiente.modelo.AddressModel;
import co.gov.minambiente.modelo.DateModel;
import co.gov.minambiente.modelo.InterestedModel;
import co.gov.minambiente.modelo.RequestModel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;

/**
 *
 * @author valer
 */
public class GraficoPorRango extends javax.swing.JFrame {
    ControlStatistics controladorEstadisticas;
    boolean estado = false;
    /**
     * Creates new form GraficoPorRango
     */
    public GraficoPorRango() {
        initComponents();
        controladorEstadisticas = new ControlStatistics();
        this.setLocationRelativeTo(null);
        this.setTitle("Estadísticas por Rango");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Grafico = new javax.swing.JLabel();
        Day = new javax.swing.JLabel();
        Month = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DayInfo = new javax.swing.JSpinner();
        YearInfo = new javax.swing.JSpinner();
        MonthInfo = new javax.swing.JSpinner();
        txtInfo = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        FechaInicial = new javax.swing.JLabel();
        FechaFinal = new javax.swing.JLabel();
        CrearGrafico = new javax.swing.JButton();
        Day1 = new javax.swing.JLabel();
        DayInfo2 = new javax.swing.JSpinner();
        Month1 = new javax.swing.JLabel();
        MonthInfo2 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        YearInfo2 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(java.awt.Color.white);

        Grafico.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        Grafico.setText("GRAFICO POR RANGO");
        Grafico.setToolTipText("");

        Day.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Day.setText("Dia");

        Month.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Month.setText("Mes");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setText("Año");

        DayInfo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        YearInfo.setModel(new javax.swing.SpinnerNumberModel(2000, 1, 2030, 1));

        MonthInfo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        MonthInfo.setToolTipText("");

        txtInfo.setBackground(java.awt.Color.white);
        txtInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInfo.setText("  ");

        BackButton.setText("Menú");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setPreferredSize(new java.awt.Dimension(748, 400));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        FechaInicial.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        FechaInicial.setText("Fecha Inicial");

        FechaFinal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        FechaFinal.setText("Fecha Final");

        CrearGrafico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CrearGrafico.setText("Crear Grafico");
        CrearGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearGraficoActionPerformed(evt);
            }
        });

        Day1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Day1.setText("Dia");

        DayInfo2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        Month1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Month1.setText("Mes");

        MonthInfo2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        MonthInfo2.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setText("Año");

        YearInfo2.setModel(new javax.swing.SpinnerNumberModel(2000, 1, 2030, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Day)
                        .addGap(18, 18, 18)
                        .addComponent(DayInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Month)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MonthInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addGap(170, 170, 170)
                        .addComponent(Grafico)))
                .addGap(18, 18, 18)
                .addComponent(YearInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Day1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DayInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Month1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MonthInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(YearInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(FechaInicial)
                        .addGap(371, 371, 371))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(CrearGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FechaFinal)
                .addGap(419, 419, 419))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(BackButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Grafico, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(FechaInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Day)
                    .addComponent(DayInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month)
                    .addComponent(MonthInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addComponent(FechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Day1)
                    .addComponent(DayInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month1)
                    .addComponent(MonthInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(CrearGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearGraficoActionPerformed
        boolean estado = true;
        repaint();
        try {
            if(estado == true){
                int daySelectedInicial =  (int) DayInfo.getValue();
                int monthSelectedInicial =  (int) MonthInfo.getValue();
                int yearSelectedInicial =  (int) YearInfo.getValue();
                DateModel fechaInicioRango = new DateModel(yearSelectedInicial, monthSelectedInicial, daySelectedInicial);
                
                int daySelectedFinal =  (int) DayInfo2.getValue();
                int monthSelectedFinal =  (int) MonthInfo2.getValue();
                int yearSelectedFinal =  (int) YearInfo2.getValue();
                DateModel fechaFinRango = new DateModel(yearSelectedFinal, monthSelectedFinal, daySelectedFinal);
                ArrayList<RequestModel> datos = RequestsDatabase.getDatabase();
              //para probar
//                ArrayList<RequestModel> datos = new ArrayList <>();
//                RequestModel modeloForm = new RequestModel("");  
//                InterestedModel interested = new InterestedModel();
//                AddressModel direc = new AddressModel();
//                direc.setDepartment("Antioquia");
//                RequestModel modeloForm1 = new RequestModel("");  
//                InterestedModel interested1= new InterestedModel();
//                AddressModel direc1 = new AddressModel();
//                direc1.setDepartment("Cundinamarca");
//                RequestModel modeloForm2 = new RequestModel("");  
//                InterestedModel interested2= new InterestedModel();
//                AddressModel direc2 = new AddressModel();
//                direc2.setDepartment("Quindio");
//
//                modeloForm.setCreationDate(new DateModel(2000, 1, 1));
//                interested.setAdress(direc);
//                modeloForm.setInterested(interested);
//                modeloForm1.setCreationDate(new DateModel(2000, 1, 1));
//                interested1.setAdress(direc1);
//                modeloForm1.setInterested(interested1);
//                modeloForm2.setCreationDate(new DateModel(2022, 1, 1));
//                interested2.setAdress(direc2);
//                modeloForm2.setInterested(interested2);
//                datos.add (modeloForm);
//                datos.add (modeloForm);
//                datos.add (modeloForm);
//                datos.add (modeloForm2);
//                datos.add (modeloForm2);
//                datos.add (modeloForm1);
//                datos.add (modeloForm1);
//                datos.add (modeloForm1);
//                datos.add (modeloForm1);
//                datos.add (modeloForm1);
//                datos.add (modeloForm1);
//                datos.add (modeloForm1);
              //finaliza los datos de prueba 
                ArrayList<RequestModel> datosFiltradosPorFecha = controladorEstadisticas.filterDataByRange(datos, fechaInicioRango, fechaFinRango);
                jPanel1.removeAll();
                jPanel1.setPreferredSize(new Dimension(748, 400));
                if(!datosFiltradosPorFecha.isEmpty()){
                    txtInfo.setText(" ");
                    ArrayList<RequestFrequency> frecuenciasPorDepartamento = controladorEstadisticas.frequencyByDeparmet(datosFiltradosPorFecha);
                    
                    JFreeChart graficoDeBarras = ChartFactory.createBarChart3D(
                            "Solicitudes por departamento", "Departamentos",
                            "Solicitudes", controladorEstadisticas.crearDataset(frecuenciasPorDepartamento),
                            PlotOrientation.VERTICAL, false, false, false);
                    
                    ChartPanel panelDelGrafico = new ChartPanel(graficoDeBarras);
                    panelDelGrafico.setMouseWheelEnabled(true);
                    panelDelGrafico.setPreferredSize(new Dimension(748, 400));
                    
                    jPanel1.setLayout(new BorderLayout());
                    jPanel1.add(panelDelGrafico, BorderLayout.NORTH);
                    
                    pack();
                    repaint();
                    
                }else{
                    txtInfo.setText("No se encontraron registros para el rango ingresado.");
                }
                
            }
        }        
        
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_CrearGraficoActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        new Principal().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CrearGrafico;
    private javax.swing.JLabel Day;
    private javax.swing.JLabel Day1;
    private javax.swing.JSpinner DayInfo;
    private javax.swing.JSpinner DayInfo2;
    private javax.swing.JLabel FechaFinal;
    private javax.swing.JLabel FechaInicial;
    private javax.swing.JLabel Grafico;
    private javax.swing.JLabel Month;
    private javax.swing.JLabel Month1;
    private javax.swing.JSpinner MonthInfo;
    private javax.swing.JSpinner MonthInfo2;
    private javax.swing.JSpinner YearInfo;
    private javax.swing.JSpinner YearInfo2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtInfo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void paint (Graphics grafico){
    
        super.paint(grafico);
        
        try {
            if(estado == true){
                int daySelectedInicial =  (int) DayInfo.getValue();
                int monthSelectedInicial =  (int) MonthInfo.getValue();
                int yearSelectedInicial =  (int) YearInfo.getValue();
                DateModel fechaInicioRango = new DateModel(yearSelectedInicial, monthSelectedInicial, daySelectedInicial);
                
                int daySelectedFinal =  (int) DayInfo2.getValue();
                int monthSelectedFinal =  (int) MonthInfo2.getValue();
                int yearSelectedFinal =  (int) YearInfo2.getValue();
                DateModel fechaFinRango = new DateModel(yearSelectedFinal, monthSelectedFinal, daySelectedFinal);
                ArrayList<RequestModel> datos = RequestsDatabase.getDatabase();
              //para probar
//                ArrayList<RequestModel> datos = new ArrayList <>();
//                RequestModel modeloForm = new RequestModel("");  
//                InterestedModel interested = new InterestedModel();
//                AddressModel direc = new AddressModel();
//                direc.setDepartment("Antioquia");
//                RequestModel modeloForm1 = new RequestModel("");  
//                InterestedModel interested1= new InterestedModel();
//                AddressModel direc1 = new AddressModel();
//                direc1.setDepartment("Cundinamarca");
//                RequestModel modeloForm2 = new RequestModel("");  
//                InterestedModel interested2= new InterestedModel();
//                AddressModel direc2 = new AddressModel();
//                direc2.setDepartment("Quindio");
//
//                modeloForm.setCreationDate(new DateModel(2000, 1, 1));
//                interested.setAdress(direc);
//                modeloForm.setInterested(interested);
//                modeloForm1.setCreationDate(new DateModel(2000, 1, 1));
//                interested1.setAdress(direc1);
//                modeloForm1.setInterested(interested1);
//                modeloForm2.setCreationDate(new DateModel(2022, 1, 1));
//                interested2.setAdress(direc2);
//                modeloForm2.setInterested(interested2);
//                datos.add (modeloForm);
//                datos.add (modeloForm);
//                datos.add (modeloForm);
//                datos.add (modeloForm2);
//                datos.add (modeloForm2);
//                datos.add (modeloForm1);
//                datos.add (modeloForm1);
//                datos.add (modeloForm1);
//                datos.add (modeloForm1);
//                datos.add (modeloForm1);
//                datos.add (modeloForm1);
//                datos.add (modeloForm1);
              //finaliza los datos de prueba 
                ArrayList<RequestModel> datosFiltradosPorFecha = controladorEstadisticas.filterDataByRange(datos, fechaInicioRango, fechaFinRango);
                jPanel1.removeAll();
                jPanel1.setPreferredSize(new Dimension(748, 400));
                if(!datosFiltradosPorFecha.isEmpty()){
                    txtInfo.setText(" ");
                    ArrayList<RequestFrequency> frecuenciasPorDepartamento = controladorEstadisticas.frequencyByDeparmet(datosFiltradosPorFecha);
                    
                    JFreeChart graficoDeBarras = ChartFactory.createBarChart3D(
                            "Solicitudes por departamento", "Departamentos",
                            "Solicitudes", controladorEstadisticas.crearDataset(frecuenciasPorDepartamento),
                            PlotOrientation.VERTICAL, false, false, false);
                    
                    ChartPanel panelDelGrafico = new ChartPanel(graficoDeBarras);
                    panelDelGrafico.setMouseWheelEnabled(true);
                    panelDelGrafico.setPreferredSize(new Dimension(748, 400));
                    
                    jPanel1.setLayout(new BorderLayout());
                    jPanel1.add(panelDelGrafico, BorderLayout.NORTH);
                    
                    pack();
                    repaint();
                    
                }else{
                    txtInfo.setText("No se encontraron registros para el rango ingresado.");
                }
                
            }
        }        
        
        catch(Exception e){
            System.out.println(e);
        }
}
}
