/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.gov.minambiente.vista.formulario;

import co.gov.minambiente.controlador.ControlStatistics;
import co.gov.minambiente.controlador.RequestFrequency;
import co.gov.minambiente.controlador.database.RequestsDatabase;
import co.gov.minambiente.modelo.AddressModel;
import co.gov.minambiente.modelo.DateModel;
import co.gov.minambiente.modelo.InterestedModel;
import co.gov.minambiente.modelo.RequestModel;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author valer
 */
public class Grafico extends javax.swing.JFrame {

    /**
     * Creates new form Grafico
     */
    
    ControlStatistics controladorEstadisticas; 
    boolean estado = false;
    
    public Grafico() {
        initComponents();
        controladorEstadisticas = new ControlStatistics();
        this.setLocationRelativeTo(null);
        this.setTitle("Grafico");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grafico = new javax.swing.JLabel();
        CrearGrafico = new javax.swing.JButton();
        Day = new javax.swing.JLabel();
        Month = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DayInfo = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        MonthInfo = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Grafico.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        Grafico.setText("GRAFICO");
        Grafico.setToolTipText("");

        CrearGrafico.setText("Crear Grafico");
        CrearGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearGraficoActionPerformed(evt);
            }
        });

        Day.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Day.setText("Dia");

        Month.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Month.setText("Mes");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setText("Año");

        DayInfo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 2030, 1));

        MonthInfo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        MonthInfo.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CrearGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(Grafico))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Day)
                        .addGap(18, 18, 18)
                        .addComponent(DayInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(Month)
                        .addGap(18, 18, 18)
                        .addComponent(MonthInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Grafico)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Month)
                    .addComponent(jLabel3)
                    .addComponent(Day)
                    .addComponent(DayInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(CrearGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearGraficoActionPerformed
        estado = true;
        repaint();
    }//GEN-LAST:event_CrearGraficoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearGrafico;
    private javax.swing.JLabel Day;
    private javax.swing.JSpinner DayInfo;
    private javax.swing.JLabel Grafico;
    private javax.swing.JLabel Month;
    private javax.swing.JSpinner MonthInfo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables

   

    @Override
    public void paint (Graphics Grafico){
    
        super.paint(Grafico);
        
        try {
            if(estado == true){
                
              //ArrayList<RequestModel> datos = RequestsDatabase.getDatabase();
              //para probar
                ArrayList<RequestModel> datos = new ArrayList <>();
                RequestModel modeloForm = new RequestModel("");  
                InterestedModel interested = new InterestedModel();
                AddressModel direc = new AddressModel();
                direc.setDepartment("Antioquia");
                RequestModel modeloForm1 = new RequestModel("");  
                InterestedModel interested1= new InterestedModel();
                AddressModel direc1 = new AddressModel();
                direc1.setDepartment("Cundinamarca");

                modeloForm.setCreationDate(new DateModel(2000, 12, 1));
                interested.setAdress(direc);
                modeloForm.setInterested(interested);
                modeloForm1.setCreationDate(new DateModel(2000, 12, 1));
                interested1.setAdress(direc1);
                modeloForm1.setInterested(interested1);
                datos.add (modeloForm);
                datos.add (modeloForm);
                datos.add (modeloForm);
                datos.add (modeloForm1);
                datos.add (modeloForm1);
                datos.add (modeloForm1);
                datos.add (modeloForm1);
                datos.add (modeloForm1);
                datos.add (modeloForm1);
                datos.add (modeloForm1);
              //finaliza los datos de prueba 
                ArrayList<RequestModel> datosFiltradosPorFecha = controladorEstadisticas.filterDataByDate(datos, new DateModel(2000, 12, 1));
                ArrayList<RequestFrequency> frecuenciasPorDepartamento = controladorEstadisticas.frequencyByDeparmet(datosFiltradosPorFecha);
                frecuenciasPorDepartamento = controladorEstadisticas.setFrequencyWidths(frecuenciasPorDepartamento, 500);

                controladorEstadisticas.paintBars(Grafico, frecuenciasPorDepartamento, 200, 300, 200, 50, Color.darkGray);
                 
            }
        }        
        
        catch(Exception e){
            System.out.println(e);
        }
}

}


