/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.gov.minambiente.vista.formulario;

import co.gov.minambiente.controlador.ControlStatistics;
import co.gov.minambiente.controlador.RequestFrequency;
import co.gov.minambiente.controlador.database.RequestsDatabase;
import co.gov.minambiente.modelo.AddressModel;
import co.gov.minambiente.modelo.DateModel;
import co.gov.minambiente.modelo.InterestedModel;
import co.gov.minambiente.modelo.RequestModel;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author valeria
 */
public class Grafico extends javax.swing.JFrame {

    /**
     * Creates new form Grafico
     */
    
    ControlStatistics controladorEstadisticas;
    boolean estado = false;
    
    public Grafico() {
        initComponents();
        controladorEstadisticas = new ControlStatistics();
        this.setLocationRelativeTo(null);
        this.setTitle("Grafico");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grafico = new javax.swing.JLabel();
        CrearGrafico = new javax.swing.JButton();
        Day = new javax.swing.JLabel();
        Month = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DayInfo = new javax.swing.JSpinner();
        YearInfo = new javax.swing.JSpinner();
        MonthInfo = new javax.swing.JSpinner();
        txtInfo = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Grafico.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        Grafico.setText("GRAFICO");
        Grafico.setToolTipText("");

        CrearGrafico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CrearGrafico.setText("Crear Grafico");
        CrearGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearGraficoActionPerformed(evt);
            }
        });

        Day.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Day.setText("Dia");

        Month.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Month.setText("Mes");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setText("Año");

        DayInfo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        YearInfo.setModel(new javax.swing.SpinnerNumberModel(2000, 1, 2030, 1));

        MonthInfo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        MonthInfo.setToolTipText("");

        txtInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInfo.setText("  ");

        BackButton.setText("Menú");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BackButton)
                                .addGap(298, 298, 298)
                                .addComponent(Grafico))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(Day)
                                .addGap(18, 18, 18)
                                .addComponent(DayInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)
                                .addComponent(Month)
                                .addGap(18, 18, 18)
                                .addComponent(MonthInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addComponent(YearInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CrearGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(341, 341, 341))
                    .addComponent(txtInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Grafico)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addGap(14, 14, 14)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Month)
                    .addComponent(jLabel3)
                    .addComponent(Day)
                    .addComponent(DayInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(txtInfo)
                .addGap(15, 15, 15)
                .addComponent(CrearGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(600, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearGraficoActionPerformed
        estado = true;
        repaint();
    }//GEN-LAST:event_CrearGraficoActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
       this.dispose();
       new Principal().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CrearGrafico;
    private javax.swing.JLabel Day;
    private javax.swing.JSpinner DayInfo;
    private javax.swing.JLabel Grafico;
    private javax.swing.JLabel Month;
    private javax.swing.JSpinner MonthInfo;
    private javax.swing.JSpinner YearInfo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtInfo;
    // End of variables declaration//GEN-END:variables

   

    @Override
    public void paint (Graphics grafico){
    
        super.paint(grafico);
        
        try {
            if(estado == true){
                int daySelected =  (int) DayInfo.getValue();
                int monthSelected =  (int) MonthInfo.getValue();
                int yearSelected =  (int) YearInfo.getValue();
              //ArrayList<RequestModel> datos = RequestsDatabase.getDatabase();
              //para probar
                ArrayList<RequestModel> datos = new ArrayList <>();
                RequestModel modeloForm = new RequestModel("");  
                InterestedModel interested = new InterestedModel();
                AddressModel direc = new AddressModel();
                direc.setDepartment("Antioquia");
                RequestModel modeloForm1 = new RequestModel("");  
                InterestedModel interested1= new InterestedModel();
                AddressModel direc1 = new AddressModel();
                direc1.setDepartment("Cundinamarca");
                RequestModel modeloForm2 = new RequestModel("");  
                InterestedModel interested2= new InterestedModel();
                AddressModel direc2 = new AddressModel();
                direc2.setDepartment("Quindio");

                modeloForm.setCreationDate(new DateModel(2000, 1, 1));
                interested.setAdress(direc);
                modeloForm.setInterested(interested);
                modeloForm1.setCreationDate(new DateModel(2000, 1, 1));
                interested1.setAdress(direc1);
                modeloForm1.setInterested(interested1);
                modeloForm2.setCreationDate(new DateModel(2022, 1, 1));
                interested2.setAdress(direc2);
                modeloForm2.setInterested(interested2);
                datos.add (modeloForm);
                datos.add (modeloForm);
                datos.add (modeloForm);
                datos.add (modeloForm2);
                datos.add (modeloForm2);
                datos.add (modeloForm1);
                datos.add (modeloForm1);
                datos.add (modeloForm1);
                datos.add (modeloForm1);
                datos.add (modeloForm1);
                datos.add (modeloForm1);
                datos.add (modeloForm1);
              //finaliza los datos de prueba 
                ArrayList<RequestModel> datosFiltradosPorFecha = controladorEstadisticas.filterDataByDate(datos, new DateModel(yearSelected, monthSelected, daySelected));
                if(!datosFiltradosPorFecha.isEmpty()){
                    txtInfo.setText(" ");
                    ArrayList<RequestFrequency> frecuenciasPorDepartamento = controladorEstadisticas.frequencyByDeparmet(datosFiltradosPorFecha);
                    frecuenciasPorDepartamento = controladorEstadisticas.setFrequencyWidths(frecuenciasPorDepartamento, 500);

                    controladorEstadisticas.paintBars(grafico, frecuenciasPorDepartamento, 200, 250, 36, 50, new Color(51, 208, 153));
                 
                }else{
                    txtInfo.setText("No se encontraron registros para la fecha ingresada.");
                }
                
            }
        }        
        
        catch(Exception e){
            System.out.println(e);
        }
}

}


